version: '3.8'
services:
  plex_debrid:
    container_name: plex_debrid
    build: .
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Africa/Johannesburg
    ports:
      - "8008:8008"
    restart: unless-stopped
    volumes:
      - ./config:/app/config:rw
      - /mnt:/mnt
      - ./settings.json:/app/settings.json:rw  # optional, for legacy migration
